[package]
name = "polkacli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies]
clap = "4.1.9"
toml = "0.7.3"
